# Generated by Django 5.0.4 on 2025-08-18 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_full_name_alter_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
