# Generated by Django 5.0.4 on 2025-08-22 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_meal_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='date_created',
        ),
    ]
